### ISSUE TITLE
regressions from https://github.com/projectatomic/bubblewrap/pull/101

### ISSUE THREAD

**Issue by cgwalters** [projectatomic/bubblewrap#197]
https://github.com/projectatomic/bubblewrap/pull/101 broke things for rpm-ostree.

See https://github.com/projectatomic/rpm-ostree/issues/855

For now: https://github.com/CentOS/sig-atomic-buildscripts/commit/a425646ce73faa7a7056e03888f557b3121dba71

**Comment by jlebon** [comment]
Or should there be a `--cap-keep` to leave capabilities untouched? E.g. if you're already managing caps through a higher level tool like systemd-nspawn.

**Comment by cgwalters** [comment]
I don't think we can change the semantics; we need to add new command line arguments.

**Comment by giuseppe** [comment]
the problem is that bwrap in setuid mode is already resetting the caps, so the two variants of bwrap work in a different way, one resets the caps and another left all the caps set. @alexlarsson asked me to include this change in the PR (which wasn't originally) to address exactly this problem and have the two versions work in the same way.

**Comment by alexlarsson** [comment]
Not having all caps by default was the entire point of bwrap and why the --caps-add where added. We just regressed on this at some point.

**Comment by cgwalters** [comment]
Sure, I understand that *when run as non-root*.  But the rpm-ostree case makes sense I think.  Yes...we could try to sandbox RPM scriptlets more.  Given the way rpm-ostree works, we could at least drop CAP_SYS_ADMIN.  I suspect it's actually just the case we hit of `CAP_DAC_OVERRIDE` for `gshadow` that's going to require some work.

But the point is - the flatpak case is just one user of bwrap.  We already have one other use case that broke.  And given all of the comments here on github from various people, we have *no idea* how many other users there are and what they're doing.

Given that we broke one (again IMO valid) use case, I think that strongly argues for reverting the change and reintroducing it compatibly.

**Comment by giuseppe** [comment]
would be enough (and acceptable) to imply `--cap-add ALL` when run by root?

**Comment by cgwalters** [comment]
That sounds reasonable to me yep.

**Comment by giuseppe** [comment]
thinking more of it, should `--uid 0` imply `--cap-add ALL`?  It is probably the least surprise to have capabilities in the sandbox when running as root (at least when it is supported: not setuid or root runs it).  if you are both fine with this approach, I can prepare a patch.

**Comment by jlebon** [comment]
> Sure, I understand that when run as non-root. But the rpm-ostree case makes sense I think.

> Given that we broke one (again IMO valid) use case, I think that strongly argues for reverting the change to drop caps at least when invoked by a privileged caller.

Though note that bwrap as called by rpm-ostree today is considered unprivileged (since #122). So, is there something to actually revert here? It seems like we're all agreeing that we should drop caps by default in the unprivileged case, which is essentially the only thing #101 changed in the regard. As for privileged users, both now and before #101, we dropped caps. The rpm-ostree case is hit by #101 due to the fact that we're considered unprivileged.

So it seems like what we want to do here is to (1) revert #122, and (2) introduce a *new* switch like `--cap-keep` which rpm-ostree can use to avoid the `capset()` call. That way, the only actual API break is that unprivileged callers lose caps by default, which is what we want. Does that make sense?

**Comment by cgwalters** [comment]
I'm still very skeptical of anything that involves changing rpm-ostree, since other people may be doing similar things.

**Comment by jlebon** [comment]
So if we want to keep the unprivileged root workflow working, I think the semantic we want is close to what @giuseppe suggested:

> would be enough (and acceptable) to imply --cap-add ALL when run by root?

But instead of `--cap-add ALL`, we imply a new `--keep-caps` which just leaves caps untouched.

**Comment by cgwalters** [comment]
PR in https://github.com/projectatomic/bubblewrap/pull/205
