### ISSUE TITLE
convert bubblewrap options to user getopt

### ISSUE THREAD

**Issue by marcosps** [projectatomic/bubblewrap#225]
Currently, the options handling is confusing. What do you think about using getopt to better organize the code? Yes you agree, I start working into this right away.

**Comment by smcv** [comment]
I believe the justification for not using `getopt_long`, and hence not supporting the `--option=value` syntax, is simplicity. Yes, it's repetitive; but it's also straightforward to reason about.

`bwrap` is setuid root on some systems, making it a dangerous attack surface. It isn't enough for it to be correct; everything that it pulls in needs to be *obviously* correct. That's why it doesn't use GLib (which is too large to audit), and that's why it uses a minimum of glibc code (mostly syscall wrappers rather than high-level stuff).

**Comment by marcosps** [comment]
Good point. I'll find another thing to work on bubblewrap. Thanks @smcv
