### ISSUE TITLE
Refactor to C++?

### ISSUE THREAD

**Issue by amtlib-dot-dll** [projectatomic/bubblewrap#254]
According to #224, there has been memory leaks in `bwrap`, and there might be more. C++ with smart pointers might be a good solution.

According to #104 and #248, ordering of the mount-points are requested. This might involve the use of hashmaps and/or path comparisons, and there would be no need to reinventing the wheel as there are hashmap libraries and filesystem libraries in the STL.

`bubblewrap` does not need to access raw hardware, so C is not a necessity. As more and more features introduced into this project, the complexity may overwhelm the simple functions in C.

Thank you very much!

**Comment by fancytenseletters** [comment]
Well, we have memory-safe languages this days. Just sayin.

**Comment by amtlib-dot-dll** [comment]
The syntax to call system API in other memory-safe languages like Rust are not as straight-forward as C++ 🤔

**Comment by smcv** [comment]
bubblewrap has to be setuid root on some OS distributions, so library dependencies (e.g. libstdc++/the STL) and implicit behaviours (e.g. C++ constructors) are not necessarily such a good idea.

> there has been memory leaks in `bwrap`

bwrap doesn't allocate a whole lot of memory anyway, and isn't carrying out any long-running operations other than "wait for child process to exit"; so even if every allocation was leaked, that would still only be O(1).

> As more and more features introduced into this project, the complexity may overwhelm the simple functions in C.

If bubblewrap grows enough complexity that "plain C" is a problem, then that's a sign that something has gone wrong somewhere. Because bubblewrap sometimes has elevated privileges (setuid root), the design principle should be that the complexity happens in a parent process like flatpak.

For instance, seccomp is normally used by linking to libseccomp, compiling a binary representation ofthe seccomp rules, and passing that blob to the kernel via a syscall; but the way this works in flatpak/bubblewrap is that **flatpak** links to libseccomp and compiles the binary representation, then passes it to bwrap as a file descriptor, with bwrap only doing the part that absolutely needs to happen in bwrap (the syscall to upload it to the kernel).

**Comment by amtlib-dot-dll** [comment]
Memory leaks are not only a performance problem; it _IS_ a possible attack surface. If we need a `libbubblewrap`, why don't we use `glibc` directly? Bubblewrap is just a caller of `unshare`. `bwrap` does not need to be setuid root, a filesystem capacity of CAP_SYS_ADMIN is enough, and for most distributions except Debian, user namespaces are enabled by default, so even this capacity is unnecessary. BTW, If someone is not familiar with implicit behaviors like C++ constructors, he is obviously not a good C++ programmer; good C programmers still write memory leaks, but good C++ programmers don't.

**Comment by amtlib-dot-dll** [comment]
@smcv Sorry, I didn't notice that you are a Debian developer.

**Comment by TingPing** [comment]
>  good C programmers still write memory leaks, but good C++ programmers don't.

Humans will always make mistakes and C++ is not remotely close to a language that *forces* safe behavior. This comment to be meaningful also requires that the developers who maintain this project are expected to be competent C++ developers which is not guaranteed.

Personally I think it is short-sighted and rude to go around projects asking them to rewrite it in a different language. Even if C++ is a smaller leap from C than others it is still a large undertaking and makes the assumption that the developers made a mistake and clearly didn't think through their original choice of C.

**Comment by smcv** [comment]
> `bwrap` does not need to be setuid root, a filesystem capacity of CAP_SYS_ADMIN is enough

A filesystem capability of CAP_SYS_ADMIN in the init namespace is so close to setuid root that it might as well be setuid root. CAP_SYS_ADMIN is the generic "do anything" capability, and escalating from CAP_SYS_ADMIN to full capabilities is trivial (for example you can bind-mount a file of your choice over `/bin/sh`, and wait for any privileged system service like `cron` to do something that is defined in terms of shell command-lines).

You're right to think that *some* filesystem capabilities (the ones that don't have an escalation path from the capability to full root) can be used as "a better setuid" - the classic example is making ping capable of CAP_NET_RAW - but many capabilities are powerful enough that this just gives a false sense of security.

> and for most distributions except Debian, user namespaces are enabled by default, so even this capacity is unnecessary

It's not just Debian: this project's README has other examples of distributions that disable unprivileged access to user namespaces.

Unprivileged access to user namespaces is a large attack surface: it takes parts of the kernel API that were previously restricted to highly-privileged processes (anything with a capable() check) and makes them available to ordinary users. If it was uncontroversial enough to be reasonable to enable everywhere, you're right to say that the bubblewrap executable would be unnecessary and could cease to exist, and callers of bubblewrap like Flatpak and Project Atomic could do the necessary syscalls themselves, either directly or via some library. However, I don't think we're there yet.

**Comment by cgwalters** [comment]
I agree with both smcv and giuseppe.

**Comment by amtlib-dot-dll** [comment]
I agree with posts above. Sorry for my ignorance of GCC attributes 👍 👍
