### ISSUE TITLE
Python example line

### ISSUE THREAD

**Issue by valoq** [projectatomic/bubblewrap#307]
Why is this line used twice? 
https://github.com/projectatomic/bubblewrap/blob/8f457ee2868ebfd20e311000aa472462c5ce3c84/demos/userns-block-fd.py#L32

Is this a typo?
Seems to work without this as well.

**Comment by smcv** [comment]
It's intentional: see the Python documentation for `os.execlp`. The first `bwrap` is the executable to run. The second `bwrap` is what its `argv[0]` will be, which should nearly always be the same thing as the executable to run.

If you remove the second `bwrap`, you'll be running bwrap and telling it that its name is `--unshare-all`. The result is that it won't treat `--unshare-all` as an option (for example if you change the command to be run in the container to something like `/sbin/ifconfig -a`, you'll find that it is in the same network namespace as the parent process, whereas in the current script it will be in a different network namespace with only a `lo` device).

**Comment by valoq** [comment]
Thanks for the explanation
