### ISSUE TITLE
Filter out insecure protocols

### ISSUE THREAD

**Issue by madaidan** [projectatomic/bubblewrap#319]
It would be good to add a way to filter out insecure and rarely used protocols, similar to Firejail's [protocol filter](http://man7.org/linux/man-pages/man5/firejail-profile.5.html#Security_filters) or systemd's [RestrictAddressFamilies](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#RestrictAddressFamilies=).

This can be used to prevent vulnerabilities in rarely used protocols such as [CVE-2019-8912](https://www.cvedetails.com/cve/CVE-2019-8912/).

It could be implemented as something like a `--protocol-filter` parameter that takes a list of protocol names to whitelist/blacklist.

**Comment by smcv** [comment]
`bwrap --seccomp=FD` can do this, and Flatpak makes use of this facility: it unconditionally allows AF_UNSPEC, AF_LOCAL (aka AF_UNIX), AF_INET and AF_INET6, has options to allow AF_CAN and AF_BLUETOOTH.

However, `bwrap` doesn't compile seccomp rules itself: because it acts as a security boundary (and has to be setuid root on some systems), it's desirable to keep `bwrap` and its dependencies minimal, to minimize attack surface. The current recommendation is that a higher-level facility like Flatpak is a better place to convert a user-friendly syntax for a protocol whitelist/blacklist into a seccomp ruleset.

**Comment by madaidan** [comment]
Thanks! I didn't know this could be done with regular seccomp.

**Comment by smcv** [comment]
> similar to Firejail's protocol filter or systemd's RestrictAddressFamilies

FYI, those are both implemented using seccomp too - I don't think there's any other reasonable way to get that functionality.
